### ISSUE TITLE
Event Salary: show

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Front#33]
Показывать возможную стоимость событий, смен, мест.

Пока нет публичного API - генерировать цифры случайным образом.

**Comment by kekboxer** [comment]
Стоимость мест/смен внутри события одинакова между собой?

**Comment by CAPCHIK** [comment]
Нет. Есть стоимость на событие, если никакой более не определено -рендерится для остального жта стоимость.
Если есть стоимость для смены - она транслируется во все её места. Остальные по старым правилам.
То есть от стоимости просто события можно конкретизировать смены, и затем места.
В самом конце указывается непосредственная оплата человеку, там сумма изначально должна предлагаться на основе публичной стоимости, но директор может её установить любой, написав комментарий.
