### ISSUE TITLE
Description refactoring for events

### ISSUE THREAD

**Issue by Suput** [RTUITLab/ITLab-Front#67]
On big screen event view seems to be fine
![image](https://user-images.githubusercontent.com/40500378/86960145-2507fd80-c170-11ea-86c5-9db93f35d554.png)
On small screen in event view appears one more line. It appears specially for description but when description isn't define - this line is unused
![image](https://user-images.githubusercontent.com/40500378/86960304-5d0f4080-c170-11ea-87d3-38185189959f.png)
That's screenshot when everything is correct
![image](https://user-images.githubusercontent.com/40500378/86960404-88922b00-c170-11ea-89e7-8b7aa9c06179.png)

**Comment by Suput** [comment]
На большом экране всё выглядит супер
![image](https://user-images.githubusercontent.com/40500378/86961645-9ea0eb00-c172-11ea-9960-adc9e43ea88d.png)
На мобильном устройстве появляется дополнительная линия. Она появляется специально, но когда описания нет, то линия кажется лишней
![image](https://user-images.githubusercontent.com/40500378/86961733-c1cb9a80-c172-11ea-9722-1a60141a14be.png)
Вот пример, когда линия работает корректно
![image](https://user-images.githubusercontent.com/40500378/86961757-cc862f80-c172-11ea-8ac7-d6e57036fe3a.png)

**Comment by CAPCHIK** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [События пользователя](https://trello.com/c/cpB5jICW/140-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D1%8F-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)
