### ISSUE TITLE
Hamburg reaction

### ISSUE THREAD

**Issue by Suput** [RTUITLab/ITLab-Front#68]
When hamburg is on - we can exit ONLY by clicking on hamburg or choose some label
While scrolling we can't open hamburg immediately
(For video themselves you can contact me)
[Downloads.zip](https://github.com/RTUITLab/ITLab-Front/files/4892797/Downloads.zip)

**Comment by Suput** [comment]
Если на мобильном устройстве открыть меню справа, то из неё можно выйти только если нажать на кнопку самого меню или есть выбрать пункт какого-то меню (хочется нажать на свободное от меню поле тоже (на видео показано, куда я тыкаю))
Когда прокручиваешь список событий, то нажав на меню справа прокрутка останавливается. Войти в меню можно только повторным нажатием
(За видео можно обращаться ко мне - они сейчас в zip файле)

**Comment by IvLaptev** [comment]
> Когда прокручиваешь список событий, то нажав на меню справа прокрутка останавливается. Войти в меню можно только повторным нажатием

Это стандартное поведение браузеров

**Comment by Suput** [comment]
> Это стандартное поведение браузеров

Понял. Тогда вопросов нет - оставляем
